name: Events Deepdive Demo 1
on:
  pull_request:
    types: [opened, edited]
      # - opened -> same result, different syntax
      # - edited
    branches:
      - main # main branch
      - "dev-*" # any branch that starts with dev-
      - "feat/**" # any branch that starts with feat/ and can include slashes
  workflow_dispatch:
  push:
    branches:
      - main # main branch
      - "dev-*" # any branch that starts with dev-
      - "feat/**" # any branch that starts with feat/ and can include slashes
    # paths-ignore:
    #   - ".github/workflows/*" # if any file changes inside the workflows folder the workflow doesn't run on push
    paths:
      - events-deepdive/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: ./events-deepdive-v2
      - name: Test code
        run: npm run test
        working-directory: ./events-deepdive-v2
      - name: Build code
        run: npm run build
        working-directory: ./events-deepdive-v2
      - name: Deploy project
        run: echo "Deploying..."
        working-directory: ./events-deepdive-v2