name: Lint - test - build - deploy practice project
# on: [push, workflow_dispatch]
on:
  push:
    paths:
      - "./practice-project/**"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./practice-project
jobs:
  Lint-test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "./practice-project/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build project
        run: npm run build
      - name: Deploy project somewhere over the rainbow
        run: echo "Deploying somewhere over the rainbow..."