name: Output event details on issues
on: [issues, workflow_dispatch]
jobs:
  output-issues-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output github.event context
        run: echo " ${{ toJSON(github.event) }}"