name: Reusable deploy and upload workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
      # secrets:
      #   some-secret:
      #     required: false
    outputs:
      result-of-deployment:
        description: The result of the deployment operation
        value: ${{ jobs.deploy-and-upload.outputs.outcome-of-deployment }}
jobs:
  deploy-and-upload:
    name: Deploy and upload job
    outputs:
      outcome-of-deployment: ${{ steps.id-step-set-result-output.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List downloaded files
        run: ls
      - name: Output information
        run: echo "Deploying and uploading..."
      - name: Set result output
        id: id-step-set-result-output
        run: echo "step-result=success" >> $GITHUB_OUTPUT