name: Use a reusable workflow inside this one
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    defaults:
      run:
        working-directory: controlling-workflow-and-job-execution
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: controlling-workflow-and-job-execution/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.output.cache-hit != 'true'
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    defaults:
      run:
        working-directory: controlling-workflow-and-job-execution
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: controlling-workflow-and-job-execution/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.output.cache-hit != 'true'
        run: npm ci
      - name: Test code
        id: id-step-test-code
        run: npm run test
      - name: Upload test report
        if: failure() && steps.id-step-test-code.outcome == 'failure' # ${{}} syntax not needed in if statements. failure() is needed to get past a failing step and the conclusion makes sure that it was the tests that failed and not dependency installation for example
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: controlling-workflow-and-job-execution/test.json
  build:
    defaults:
      run:
        working-directory: controlling-workflow-and-job-execution
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: controlling-workflow-and-job-execution/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.output.cache-hit != 'true'
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Print folder contents
        run: ls
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: controlling-workflow-and-job-execution/dist
  deploy:
    needs: build
    uses: ./.github/workflows/reusable-deploy-and-upload.yml
    with:
      artifact-name: dist-files
  report-if-something-failed:
    name: Report if something failed
    needs: [lint, deploy]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Output information
        run: |  
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"
